name: Update Post List
on:
  push:
    paths:
      - 'content/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate posts.json
        run: |
          echo "[" > posts.json
          for file in $(ls content/*.md -1t); do
            filename=$(basename "$file" .md)
            title=$(head -n 1 "$file" | sed 's/# //')
            echo "  {\"title\": \"$title\", \"slug\": \"$filename\"}," >> posts.json
          done
          sed -i '$ s/,$//' posts.json
          echo "]" >> posts.json
      - name: Generate posts_problem.json
        run: |
          echo "[" > posts_problem.json
          for file in $(ls content_problem/*.md -1t); do
            filename=$(basename "$file" .md)
            title=$(head -n 1 "$file" | sed 's/# //')
            echo "  {\"title\": \"$title\", \"slug\": \"$filename\"}," >> posts_problem.json
          done
          sed -i '$ s/,$//' posts_problem.json
          echo "]" >> posts_problem.json
      - name: Generate posts_contest.json
        run: |
          echo "[" > posts_contest.json
          for file in $(ls content_contest/*.md -1t); do
            filename=$(basename "$file" .md)
            title=$(head -n 1 "$file" | sed 's/# //')
            echo "  {\"title\": \"$title\", \"slug\": \"$filename\"}," >> posts_contest.json
          done
          sed -i '$ s/,$//' posts_contest.json
          echo "]" >> posts_contest.json
      - name: Generate posts_docs.json
        run: |
          echo "[" > posts_docs.json
          for file in $(ls content_docs/*.md -1t); do
            filename=$(basename "$file" .md)
            title=$(head -n 1 "$file" | sed 's/# //')
            echo "  {\"title\": \"$title\", \"slug\": \"$filename\"}," >> posts_docs.json
          done
          sed -i '$ s/,$//' posts_docs.json
          echo "]" >> posts_docs.json
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts.json
          git commit -m "Bot: Cập nhật danh sách bài viết" || exit 0
          git push